### ISSUE TITLE
unity 2018.2.0b9 - `Mathematics' does not exist in the namespace

### ISSUE THREAD

**Issue by wlstks7** [keijiro/TestbedHDRP#1]
Unity 2018.2.0b9 version 

Assets/LightGrid/LightGrid.cs(3,13): error CS0234: The type or namespace name `Mathematics' does not exist in the namespace `Unity'. Are you missing an assembly reference?

**Comment by keijiro** [comment]
It should be automatically imported via the Package Manager.

https://github.com/keijiro/TestbedHDRP/blob/master/Packages/manifest.json#L3

Could you retry opening the project few more time? I suspect that the package server is down.

**Comment by keijiro** [comment]
I suspect that there is another problem with your environment.

Could you check if you can create a project from the HDRP template?

https://blogs.unity3d.com/2018/04/26/how-to-get-the-most-out-of-the-new-unity-project-templates-in-2018-1/

**Comment by moebiussurfing** [comment]
i am having the same error. I justa dragged the full folder to an empty project and opened some of the scenes

**Comment by keijiro** [comment]
@moebiussurfing Just drag-and-dropping the full folder doesn't work. You also have to copy the package manifest file.

https://github.com/keijiro/TestbedHDRP/blob/master/Packages/manifest.json

**Comment by moebiussurfing** [comment]
ok. but sorry I am very newbee... what I have to do wtih the manifest file? I dragged to the assets window... Also opened with VS 2017 but nothing changes... same errors

**Comment by keijiro** [comment]
Close Unity Editor and copy manifest.json to the `Packages` directory, not the `Assets` directory.

**Comment by moebiussurfing** [comment]
thanks @keijiro , and sorry for boring you..

**Comment by keijiro** [comment]
@moebiussurfing You shouldn't use the zip download because it lacks submodules. It's recommended using Git to use the submodules correctly.

https://blog.github.com/2016-02-01-working-with-submodules/

I'm closing this issue ticket because the current context is not relevant to the topic. Please feel free to open a new issue for further questions.
