### ISSUE TITLE
HDRP shader help ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [keijiro/TestbedHDRP#10]
hello,

i can't find any documentation about HDRP shading ...
i have an Fur shader ... how can i convert this to HDRP?
can you help me? i've attached the shader ... can you convert this to HDRP please?

thank a lot ...

[Fur.zip](https://github.com/keijiro/TestbedHDRP/files/2389164/Fur.zip)

**Comment by keijiro** [comment]
https://github.com/Unity-Technologies/ScriptableRenderPipeline/wiki
