### ISSUE TITLE
Voxelizer shaders apears to be broken.

### ISSUE THREAD

**Issue by Kulgann** [keijiro/TestbedHDRP#12]
Hi, I tried importing the Voxelizer shader in unity 2018.2.5f1 using HDRP 3.0.0.
I needed to revert the latest  changes so that ENCODE_INTO_GBUFFER() would get the right params but I get a completely black object that turns strangely transparent when it moves. I'm providing a screenshot.
![broken voxilezer](https://user-images.githubusercontent.com/4999276/47306262-9a4a3c80-d634-11e8-9581-54797484fdc1.png)

**Comment by keijiro** [comment]
This repository currently maintained with Unity 2018.3.0 and HDRP 3.3.0. It may not work on other versions because HDRP is under heavy development and has many compatibility-breaking changes between versions.

I'd recommend using the revision at c641e6b82c if you'd like to use HDRP 3.0.0. It's the last commit before updating to 3.3.0.

**Comment by keijiro** [comment]
Okay. Some thoughts:

- The custom shaders only support deferred lighting path (with FPTL), so if you're using the force-forward mode, it will get black. I'd recommend checking if it works with the default HDRP settings.
- The custom shaders don't affect bounding boxes. It's recommended to expand the bounding box when using these kinds of animated effects to avoid being culled.

**Comment by Kulgann** [comment]
> Okay. Some thoughts:
> 
> * The custom shaders only support deferred lighting path (with FPTL), so if you're using the force-forward mode, it will get black. I'd recommend checking if it works with the default HDRP settings.
> * The custom shaders don't affect bounding boxes. It's recommended to expand the bounding box when using these kinds of animated effects to avoid being culled.

Oh wow Yes. It seems that I had forced forward on due to some other experiments. Thank you 👍
