### ISSUE TITLE
DecalProjectorComponent error in Unity 2019.2.13f1

### ISSUE THREAD

**Issue by tusharsankhala** [keijiro/TestbedHDRP#14]
Hi,

I am getting DecalProjectorComponent compiler error while opening project. I am basically looking to learn how to implement geometry shaders in HDRP.

Error: **Assets\Basic\Decal\StickerController.cs(31,50): error CS1061: 'DecalProjectorComponent' does not contain a definition for 'm_Material' and no accessible extension method 'm_Material' accepting a first argument of type 'DecalProjectorComponent' could be found (are you missing a using directive or an assembly reference?)**

If possible can you please put one very simple geometry shader in HDRP, so that many people like me can learn from start.

Thanks in advance.

**Comment by keijiro** [comment]
HDRP doesn't guarantee perfect forward compatibility, so you might not be able to open the project with the recent versions of Unity.

I'd like to update the project when I have time, I can't afford it at the moment though.

**Comment by tusharsankhala** [comment]
Thanks for your reply.

I checked in the unity Hub that the project is created in 2019.1.7f1, so i installed and opened it in 2019.1.7f1 but i am getting issues of missing shader file.

**Error: Shader error in 'Voxelizer': failed to open source file: 'Packages/com.unity.render-pipelines.high-definition/Runtime/Material/Lit/ShaderPass/LitVelocityPass.hlsl' at line 513 (on d3d11)**

I checked the HDRP package and the file is missing.

I have also checked the HDRP package and is same as one mentioned in the packages json file.

Any idea, how can i solve this.

**Comment by keijiro** [comment]
I wrote that "Unity 2018.3 or later" on the system requirement, but now I'm pretty sure that it only runs on 2018.3 (no support on later versions).

**Comment by havocfire** [comment]
Could you update TestbedHDRP for the final HDRP version the end of January?

**Comment by keijiro** [comment]
The current status: I updated the custom shader effects and the lighting test scenes with Unity 2019.4. At the same time, I removed the other test scenes because I can't afford time for maintaining all of them.

So, the decal scene was removed. Sorry about it. Regarding the Voxelizer effect, it works correctly now.

**Comment by havocfire** [comment]
Thank you for Voxelizer.
