### ISSUE TITLE
Will this TestBedHDRP work for Unity 2020.3 ?

### ISSUE THREAD

**Issue by eloimaduell** [keijiro/TestbedHDRP#17]
I tried to open this on my OSX under Unity 2020.3.0f1 and I got a compilation error with VideoPlayer not being defined... and the project is opened in Safe Mode ?¿ Is this error because of the Unity version ? or it's because of OSX ?

This is the error I get : 

`Library/PackageCache/com.unity.render-pipelines.high-definition@10.3.2/Runtime/Compositor/CompositionLayer.cs(60,26): error CS1069: The type name 'VideoPlayer' could not be found in the namespace 'UnityEngine.Video'. This type has been forwarded to assembly 'UnityEngine.VideoModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Video' in the Package Manager window to fix this error.
`

**Comment by eloimaduell** [comment]
I've been able to open it with Unity 2019.4.23f1, so maybe the error was because it can't be upgraded to Unity 2020.3.0f1 ? or wrong HDRP version ?

**Comment by keijiro** [comment]
You can solve it by adding the built-in Video package from the Package Manager UI.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
