### ISSUE TITLE
HDRP file problem

### ISSUE THREAD

**Issue by gabriverga** [keijiro/TestbedHDRP#18]
Hi, sorry for the inconvenience. I'm trying to open your project but it doesn't work and it looks like it does in the picture. How can I do?
Thanks in advance.

Macbook Pro 2017
MacOS Big Sur
Unity 2019.4.29f1

<img width="1436" alt="Schermata 2021-09-17 alle 13 09 55" src="https://user-images.githubusercontent.com/90905428/133773212-6bf7304f-56cd-475e-8afa-b40cdcc03cd3.png">

**Comment by keijiro** [comment]
Metal on macOS doesn't support geometry shaders, so it doesn't run.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
