### ISSUE TITLE
Missing Prefab

### ISSUE THREAD

**Issue by bigssu** [keijiro/TestbedHDRP#3]
Statue file comes with missing Prefab so I can't even test it. and when I switch platform to iOS, it give me a lot of errors

**Comment by keijiro** [comment]
These files are imported via submodules. Please see the "How to use the project" section in the README.

Currently HDRP only supports desktop platforms. Please refer to the HDRP documents for further details.

**Comment by keijiro** [comment]
I'm closing this ticker. Please feel free to reopen for further questions.
