### ISSUE TITLE
it doesn't work and getting script error

### ISSUE THREAD

**Issue by bigssu** [keijiro/TestbedHDRP#5]
Assertion failed on expression: 'pass >= 0 && pass < (int)m_Passes.size()'

Unknown pass type
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

<img width="1680" alt="screenshot 2018-07-05 14 10 26" src="https://user-images.githubusercontent.com/10752265/42348200-6dacbea0-805d-11e8-93f0-b6c3073c3344.png">

**Comment by keijiro** [comment]
As far as I know, the current version of HDRP has some issues with Metal (macOS). I wonder if this is an issue in my shader or HDRP shaders.

Could you check if other scenes have the same issue? If no one works, that might be an issue with HDRP, not on my side.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by bigssu** [comment]
I just down load latest build and test with my brand new Macbook pro with Metal and still has exact same issue 
I use unity 2018.2.0f2 this time

**Comment by keijiro** [comment]
The Metal issue was fixed in the latest version of HDRP. So please update the repository before testing.

When trying this repository on Metal, you shouldn't use the custom shader examples because they require the geometry shader feature. Metal doesn't support geometry shader.
