### ISSUE TITLE
Cannot fetch the statue submodule.

### ISSUE THREAD

**Issue by faldor20** [keijiro/TestbedHDRP#7]
For some reason i cannot seem to download the sub module for the statues, i try it in something like gitkraken and it just fails and says no refernce for shorthand origin/master and command line git says: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to fetch in submodule path 'Packages/jp.keijiro.beta'

**Comment by faldor20** [comment]
actually after some diagnosis it is because it is attempting to download the upm branch which is not available to me when using ssh... im not sure why

**Comment by keijiro** [comment]
These repositories are all up and public. Please re-check if your Git client and your GitHub account is correctly set up with your SSH key. Have you ever use it with SSH? Trying cloning some repositories (not submodule) with SSH would be a good idea.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.

**Comment by faldor20** [comment]
Hello i don't think you really understand. I did thorough testing, all the other sub-modules cloned without fault, using ssh. i even cloned the main branch of the statue repo again using ssh and it worked but when i tried to switch to the upm branch it failed. no this may still be me doing something stupid, this is my first time using ssh after all :) but still i think its more than that.

**Comment by keijiro** [comment]
> Unable to fetch in submodule path 'Packages/jp.keijiro.beta'

`Packages/jp.keijiro.beta` is not the statue repo. It contains a skinned dummy humanoid model, and it only has `master` branch (no `upm` branch).

Could you clarify the following points?

- Which submodule did you fail to clone?
- Which branch did you fail to retrieve?

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.
